#line 1 "lex.yy.cpp"

#line 3 "lex.yy.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yyget_lval
#define yyget_lval_ALREADY_DEFINED
#else
#define yyget_lval yyget_lval
#endif

#ifdef yyset_lval
#define yyset_lval_ALREADY_DEFINED
#else
#define yyset_lval yyset_lval
#endif

#ifdef yyget_lloc
#define yyget_lloc_ALREADY_DEFINED
#else
#define yyget_lloc yyget_lloc
#endif

#ifdef yyset_lloc
#define yyset_lloc_ALREADY_DEFINED
#else
#define yyset_lloc yyset_lloc
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 64
#define YY_END_OF_BUFFER 65
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[240] =
    {   0,
        0,    0,    0,    0,   65,   63,    6,    7,    7,   63,
       63,   57,   63,   62,   57,   62,   59,   57,   57,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   62,
        3,    4,    6,    7,   56,    0,   61,   59,    5,   62,
       59,    1,   60,   54,   55,   53,   58,   58,   58,   43,
       58,   37,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   46,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,    2,   60,    5,    5,   60,   58,   32,   38,

       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   27,
       58,   58,   40,   41,   58,   58,   58,   25,   58,   58,
       42,   58,   58,   58,   58,   58,   60,   58,   58,   28,
       58,   58,   58,   58,   58,   17,   16,   58,   34,   58,
       58,   22,   58,   58,   35,   58,   58,   19,   33,   50,
       58,   58,   58,    8,   58,   58,   51,   58,   58,   58,
       11,    9,   58,   39,   58,   58,   58,   58,   52,   29,
       44,   58,   31,   58,   36,   58,   58,   58,   15,   58,
       58,   23,   10,   14,   58,   21,   58,   45,   18,   58,

       26,   58,   13,   24,   20,   58,   58,   58,   58,   30,
       58,   58,   12,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   47,   58,   58,   48,   58,   49,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    1,    1,    1,    1,    1,    6,    7,
        8,    9,   10,   11,   12,   13,   14,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,    1,   16,   17,
       18,   19,    1,    1,   20,   21,   22,   23,   24,   25,
       26,   27,   28,   29,   30,   31,   32,   33,   34,   35,
       36,   37,   38,   39,   40,   41,   42,   43,   44,   36,
        1,    1,    1,    1,   45,    1,   46,   47,   48,   49,

       50,   51,   52,   53,   54,   55,   56,   57,   58,   59,
       60,   61,   36,   62,   63,   64,   65,   66,   67,   68,
       69,   36,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[70] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    3,    3,    3,    1,    1,    1,    1,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3
    } ;

static const flex_int16_t yy_base[246] =
    {   0,
        0,    0,  154,  152,  149, 1372,  146, 1372,  137,  114,
      125, 1372,  114,   58,    0,  118,   59,   57,  108,   65,
       69,   77,   96,   82,  131,  122,  140,   88,  153,   93,
      157,  161,  143,  182,  231,  186,  189,  206,  198,    0,
     1372,  109,  120, 1372, 1372,  112, 1372,   72,  296,    0,
       84, 1372,  102, 1372, 1372, 1372,  215,  222,  226,  251,
      264,  247,  273,  296,  308,  311,  317,  325,  321,  332,
      339,  350,  359,  364,  375,  369,  389,  378,  401,  417,
      421,  395,  436,  443,  449,  452,  456,  463,  477,  482,
      489,  499, 1372,   77,    0,  549,   73,  255,  512,  515,

      520,  524,  531,  557,  527,  563,  567,  570,  584,  581,
      587,  591,  594,  598,  608,  611,  620,  629,  645,  648,
      654,  623,  662,  671,  676,  679,  685,  689,  692,  702,
      705,  708,  718,  731,  715,  711,   69,  740,  748,  744,
      757,  762,  770,  774,  777,  780,  783,  786,  806,  809,
      815,  818,  823,  832,  835,  838,  843,  848,  854,  857,
      860,  864,  876,  880,  887,  890,  895,  904,  907,  913,
      916,  920,  932,  935,  938,  941,  952,  960,  946,  965,
      968,  973,  977,  980,  991,  994,  999, 1004, 1008, 1015,
     1018, 1021, 1029, 1035, 1041, 1045, 1048, 1054, 1062, 1065,

     1070, 1076, 1082, 1088, 1091, 1094, 1097, 1102, 1111, 1114,
     1124, 1127, 1133, 1137, 1140, 1154, 1157, 1163, 1170, 1182,
     1186, 1199, 1206, 1210, 1225, 1228, 1233, 1239, 1246, 1242,
     1252, 1259, 1269, 1272, 1278, 1285, 1295, 1302, 1372, 1359,
     1362,   77,   68, 1365, 1368
    } ;

static const flex_int16_t yy_def[246] =
    {   0,
      239,    1,  240,  240,  239,  239,  239,  239,  239,  239,
      241,  239,  239,  242,  242,  242,  242,  239,  239,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  242,
      239,  239,  239,  239,  239,  241,  239,  239,  244,  242,
      242,  239,  242,  239,  239,  239,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  239,  239,  245,  244,  242,  243,  243,  243,

      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  239,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,

      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,    0,  239,
      239,  239,  239,  239,  239
    } ;

static const flex_int16_t yy_nxt[1442] =
    {   0,
        6,    7,    8,    9,   10,   11,   12,   12,   12,   13,
       12,   14,   15,   16,   17,   12,   18,   12,   19,   20,
       21,   22,   23,   24,   25,   26,   27,   28,   29,   30,
       31,   32,   30,   33,   30,   30,   34,   35,   36,   37,
       38,   39,   30,   30,   40,   20,   21,   22,   23,   24,
       25,   26,   27,   28,   29,   30,   31,   32,   30,   33,
       30,   34,   35,   36,   37,   38,   39,   30,   30,   49,
       57,   53,   51,   51,   54,   55,   50,   50,   50,   50,
       50,   50,   50,  137,   94,   58,   48,   97,   50,   50,
       50,  137,   61,   50,   50,   50,   53,   59,   51,   50,

       50,   50,   60,   63,   50,   50,   50,   50,   50,   50,
       64,   58,   62,   65,   69,   66,   97,   47,   61,   67,
       77,   43,   93,   59,   70,   56,   52,   60,   48,   63,
       47,   45,   68,   50,   50,   50,   64,   62,   65,   44,
       69,   66,   50,   50,   50,   67,   77,   43,  239,   70,
       71,   50,   50,   50,   50,   50,   50,   68,   74,   75,
       42,   72,   42,   76,   50,   50,   50,   73,   50,   50,
       50,  239,   50,   50,   50,  239,   71,  239,  239,   82,
       80,  239,  239,   74,  239,   75,   78,   72,   81,   76,
       79,  239,   73,   50,   50,   50,  239,   50,   50,   50,

       50,   50,   50,  239,   82,   88,   80,  239,  239,   50,
       50,   50,   78,  239,   81,   83,   79,   50,   50,   50,
      239,  239,   89,   90,   92,   91,   50,   50,   50,  239,
      239,   88,  239,   50,   50,   50,  239,   50,   50,   50,
      239,   83,   50,   50,   50,  239,  239,   89,   99,   90,
       92,   91,  239,  239,   84,   98,  239,   85,   50,   50,
       50,  239,   50,   50,   50,  239,   50,   50,   50,   86,
       87,  239,  100,  239,   99,   50,   50,   50,  239,  239,
       84,   98,  239,   85,   50,   50,   50,  239,  239,  101,
      239,  138,  102,  239,   86,   87,   95,   95,  100,   95,

       95,   95,   95,   95,   95,   95,   95,   50,   50,   50,
      239,   95,   95,   95,   95,  101,  138,  239,  102,   50,
       50,   50,   50,   50,   50,  239,  239,  103,   50,   50,
       50,  105,   50,   50,   50,  104,   50,   50,   50,  239,
      110,  239,  239,   50,   50,   50,  239,  107,  239,  106,
       50,   50,   50,  103,  108,  239,  239,  105,  109,  111,
      104,   50,   50,   50,  239,  239,  110,  239,  239,  112,
       50,   50,   50,  107,  106,   50,   50,   50,  239,  108,
       50,   50,   50,  113,  109,  111,   50,   50,   50,   50,
       50,   50,  114,  239,  239,  112,  239,  115,  239,  117,

       50,   50,   50,  239,  239,  121,   50,   50,   50,  113,
      239,  118,   50,   50,   50,  116,  239,  125,  114,  239,
      122,  239,  239,  115,  239,  117,  119,  120,   50,   50,
       50,  121,   50,   50,   50,  239,  239,  118,  239,  239,
      116,  239,  239,  125,  239,  239,  122,   50,   50,   50,
      239,  119,  120,  124,   50,   50,   50,  239,  239,  123,
       50,   50,   50,   50,   50,   50,  126,   50,   50,   50,
      239,  130,  239,  127,   50,   50,   50,  239,  239,  124,
      239,  128,  129,  132,  123,  239,  239,  131,   50,   50,
       50,  239,  126,   50,   50,   50,  239,  130,  239,  127,

       50,   50,   50,  239,  134,  239,  128,  239,  129,  132,
       50,   50,   50,  131,  239,  239,  133,  239,  239,  135,
      239,  239,  136,   50,   50,   50,   50,   50,   50,  239,
      134,   50,   50,   50,  239,   50,   50,   50,   50,   50,
       50,  133,   50,   50,   50,  135,  143,  139,  136,   95,
       95,  239,   95,   95,   95,   95,   95,   95,   95,   95,
      140,  239,  141,  239,   95,   95,   95,   95,   50,   50,
       50,  239,  143,  139,   50,   50,   50,  239,   50,   50,
       50,   50,   50,   50,  239,  140,  144,  239,  141,  142,
      145,  146,   50,   50,   50,   50,   50,   50,   50,   50,

       50,  148,   50,   50,   50,   50,   50,   50,  239,   50,
       50,   50,  144,  151,  239,  142,  145,  146,  147,   50,
       50,   50,   50,   50,   50,  149,  239,  148,  150,  152,
      239,   50,   50,   50,   50,   50,   50,  239,  154,  151,
       50,   50,   50,  239,  147,  160,  239,  153,  239,  239,
      149,  239,  156,  150,  155,  152,   50,   50,   50,   50,
       50,   50,  239,  239,  154,   50,   50,   50,  157,  239,
      239,  160,  153,   50,   50,   50,  239,  239,  156,  239,
      155,  158,   50,   50,   50,  239,  159,   50,   50,   50,
       50,   50,   50,  239,  157,  239,   50,   50,   50,  161,

       50,   50,   50,   50,   50,   50,  239,  158,  163,  162,
      239,  239,  159,   50,   50,   50,   50,   50,   50,   50,
       50,   50,   50,   50,   50,  161,   50,   50,   50,   50,
       50,   50,  239,  164,  163,  162,  239,  239,  166,  239,
      165,  167,   50,   50,   50,  239,  239,  170,  239,  239,
      168,   50,   50,   50,  169,   50,   50,   50,  164,   50,
       50,   50,  239,  239,  166,  165,  239,  167,   50,   50,
       50,  239,  170,   50,   50,   50,  168,  239,  171,  169,
      172,   50,   50,   50,  173,   50,   50,   50,   50,   50,
       50,   50,   50,   50,   50,   50,   50,   50,   50,   50,

      174,  239,  239,  171,  239,  239,  172,  239,  175,  239,
      173,  239,  176,  239,  239,  177,  178,   50,   50,   50,
       50,   50,   50,  239,  239,  174,   50,   50,   50,   50,
       50,   50,  179,  175,   50,   50,   50,  176,  239,  239,
      177,  239,  178,   50,   50,   50,   50,   50,   50,   50,
       50,   50,  239,  180,   50,   50,   50,  181,  179,   50,
       50,   50,  239,  239,  182,   50,   50,   50,   50,   50,
       50,   50,   50,   50,  239,   50,   50,   50,  180,  184,
      183,  239,  239,  181,  186,  239,  239,   50,   50,   50,
      182,   50,   50,   50,  239,  239,  185,  187,   50,   50,

       50,   50,   50,   50,  184,  183,   50,   50,   50,  239,
      186,  239,  239,  189,  188,   50,   50,   50,   50,   50,
       50,  185,  239,  187,   50,   50,   50,   50,   50,   50,
      191,   50,   50,   50,  239,  239,  192,  239,  239,  189,
      188,  239,  190,   50,   50,   50,   50,   50,   50,   50,
       50,   50,   50,   50,   50,  239,  191,   50,   50,   50,
      239,  194,  192,   50,   50,   50,  239,  190,  195,  239,
      193,   50,   50,   50,  239,  196,   50,   50,   50,   50,
       50,   50,  239,  197,   50,   50,   50,  194,   50,   50,
       50,   50,   50,   50,  195,  193,  239,  239,  198,  239,

      239,  196,   50,   50,   50,   50,   50,   50,  239,  197,
       50,   50,   50,  200,  239,   50,   50,   50,  199,   50,
       50,   50,  239,  239,  198,  202,   50,   50,   50,   50,
       50,   50,   50,   50,   50,  239,  239,  201,  204,  200,
       50,   50,   50,  199,  239,  203,   50,   50,   50,  239,
      239,  202,   50,   50,   50,  205,   50,   50,   50,   50,
       50,   50,  201,  239,  204,   50,   50,   50,  239,  239,
      203,  239,  206,   50,   50,   50,   50,   50,   50,  239,
      205,   50,   50,   50,  239,  239,  208,   50,   50,   50,
      239,  239,  207,   50,   50,   50,  239,  239,  206,   50,

       50,   50,   50,   50,   50,   50,   50,   50,   50,   50,
       50,  239,  208,   50,   50,   50,  239,  210,  239,  239,
      209,  239,   50,   50,   50,   50,   50,   50,  239,  211,
      239,  213,  214,  239,  212,   50,   50,   50,   50,   50,
       50,  239,  239,  210,   50,   50,   50,  215,   50,   50,
       50,   50,   50,   50,  239,  211,  239,  213,  214,  212,
      216,  239,  239,  217,  239,   50,   50,   50,   50,   50,
       50,  239,  239,  215,   50,   50,   50,  218,  239,  239,
      220,   50,   50,   50,  239,  239,  216,  239,  239,  217,
      219,  239,  239,   50,   50,   50,  239,   50,   50,   50,

      239,  221,  218,  223,  239,  239,  220,  239,  222,  239,
       50,   50,   50,  239,  239,  219,  224,   50,   50,   50,
      239,   50,   50,   50,  239,  239,  221,  239,  239,  223,
      225,  239,  239,  222,  239,  226,   50,   50,   50,   50,
       50,   50,  224,  227,   50,   50,   50,  239,  228,  239,
       50,   50,   50,   50,   50,   50,  225,   50,   50,   50,
      239,  226,  229,   50,   50,   50,  230,  239,  239,  227,
       50,   50,   50,  239,  228,  231,  233,  234,  239,  232,
       50,   50,   50,   50,   50,   50,  235,  239,  229,   50,
       50,   50,  230,  239,  239,  236,   50,   50,   50,  239,

      231,  239,  233,  234,  239,  232,   50,   50,   50,  239,
      237,  239,  235,   50,   50,   50,  239,  239,  239,  239,
      239,  236,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  238,  239,  239,  237,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  238,   41,
       41,   41,   46,   46,   46,   96,  239,   96,   95,  239,
       95,    5,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,

      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239
    } ;

static const flex_int16_t yy_chk[1442] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,   14,
      243,   17,   14,   17,   18,   18,   20,   20,   20,  242,
       21,   21,   21,  137,   48,   20,   48,   97,   22,   22,
       22,   94,   21,   24,   24,   24,   51,   20,   51,   28,

       28,   28,   20,   22,   30,   30,   30,   23,   23,   23,
       22,   20,   21,   22,   24,   23,   53,   46,   21,   23,
       28,   43,   42,   20,   24,   19,   16,   20,   13,   22,
       11,   10,   23,   26,   26,   26,   22,   21,   22,    9,
       24,   23,   25,   25,   25,   23,   28,    7,    5,   24,
       25,   27,   27,   27,   33,   33,   33,   23,   26,   27,
        4,   25,    3,   27,   29,   29,   29,   25,   31,   31,
       31,    0,   32,   32,   32,    0,   25,    0,    0,   33,
       32,    0,    0,   26,    0,   27,   29,   25,   32,   27,
       31,    0,   25,   34,   34,   34,    0,   36,   36,   36,

       37,   37,   37,    0,   33,   36,   32,    0,    0,   39,
       39,   39,   29,    0,   32,   34,   31,   38,   38,   38,
        0,    0,   36,   37,   39,   38,   57,   57,   57,    0,
        0,   36,    0,   58,   58,   58,    0,   59,   59,   59,
        0,   34,   35,   35,   35,    0,    0,   36,   59,   37,
       39,   38,    0,    0,   35,   58,    0,   35,   62,   62,
       62,    0,   60,   60,   60,    0,   98,   98,   98,   35,
       35,    0,   60,    0,   59,   61,   61,   61,    0,    0,
       35,   58,    0,   35,   63,   63,   63,    0,    0,   61,
        0,   98,   63,    0,   35,   35,   49,   49,   60,   49,

       49,   49,   49,   49,   49,   49,   49,   64,   64,   64,
        0,   49,   49,   49,   49,   61,   98,    0,   63,   65,
       65,   65,   66,   66,   66,    0,    0,   64,   67,   67,
       67,   65,   69,   69,   69,   64,   68,   68,   68,    0,
       69,    0,    0,   70,   70,   70,    0,   67,    0,   66,
       71,   71,   71,   64,   67,    0,    0,   65,   68,   70,
       64,   72,   72,   72,    0,    0,   69,    0,    0,   71,
       73,   73,   73,   67,   66,   74,   74,   74,    0,   67,
       76,   76,   76,   72,   68,   70,   75,   75,   75,   78,
       78,   78,   73,    0,    0,   71,    0,   74,    0,   76,

       77,   77,   77,    0,    0,   78,   82,   82,   82,   72,
        0,   77,   79,   79,   79,   75,    0,   82,   73,    0,
       79,    0,    0,   74,    0,   76,   77,   77,   80,   80,
       80,   78,   81,   81,   81,    0,    0,   77,    0,    0,
       75,    0,    0,   82,    0,    0,   79,   83,   83,   83,
        0,   77,   77,   81,   84,   84,   84,    0,    0,   80,
       85,   85,   85,   86,   86,   86,   83,   87,   87,   87,
        0,   86,    0,   84,   88,   88,   88,    0,    0,   81,
        0,   84,   85,   88,   80,    0,    0,   87,   89,   89,
       89,    0,   83,   90,   90,   90,    0,   86,    0,   84,

       91,   91,   91,    0,   90,    0,   84,    0,   85,   88,
       92,   92,   92,   87,    0,    0,   89,    0,    0,   91,
        0,    0,   92,   99,   99,   99,  100,  100,  100,    0,
       90,  101,  101,  101,    0,  102,  102,  102,  105,  105,
      105,   89,  103,  103,  103,   91,  105,  101,   92,   96,
       96,    0,   96,   96,   96,   96,   96,   96,   96,   96,
      102,    0,  103,    0,   96,   96,   96,   96,  104,  104,
      104,    0,  105,  101,  106,  106,  106,    0,  107,  107,
      107,  108,  108,  108,    0,  102,  106,    0,  103,  104,
      107,  108,  110,  110,  110,  109,  109,  109,  111,  111,

      111,  110,  112,  112,  112,  113,  113,  113,    0,  114,
      114,  114,  106,  113,    0,  104,  107,  108,  109,  115,
      115,  115,  116,  116,  116,  111,    0,  110,  112,  114,
        0,  117,  117,  117,  122,  122,  122,    0,  116,  113,
      118,  118,  118,    0,  109,  122,    0,  115,    0,    0,
      111,    0,  118,  112,  117,  114,  119,  119,  119,  120,
      120,  120,    0,    0,  116,  121,  121,  121,  119,    0,
        0,  122,  115,  123,  123,  123,    0,    0,  118,    0,
      117,  120,  124,  124,  124,    0,  121,  125,  125,  125,
      126,  126,  126,    0,  119,    0,  127,  127,  127,  125,

      128,  128,  128,  129,  129,  129,    0,  120,  127,  126,
        0,    0,  121,  130,  130,  130,  131,  131,  131,  132,
      132,  132,  136,  136,  136,  125,  135,  135,  135,  133,
      133,  133,    0,  129,  127,  126,    0,    0,  132,    0,
      130,  133,  134,  134,  134,    0,    0,  136,    0,    0,
      134,  138,  138,  138,  135,  140,  140,  140,  129,  139,
      139,  139,    0,    0,  132,  130,    0,  133,  141,  141,
      141,    0,  136,  142,  142,  142,  134,    0,  138,  135,
      139,  143,  143,  143,  141,  144,  144,  144,  145,  145,
      145,  146,  146,  146,  147,  147,  147,  148,  148,  148,

      142,    0,    0,  138,    0,    0,  139,    0,  143,    0,
      141,    0,  144,    0,    0,  145,  148,  149,  149,  149,
      150,  150,  150,    0,    0,  142,  151,  151,  151,  152,
      152,  152,  150,  143,  153,  153,  153,  144,    0,    0,
      145,    0,  148,  154,  154,  154,  155,  155,  155,  156,
      156,  156,    0,  151,  157,  157,  157,  153,  150,  158,
      158,  158,    0,    0,  154,  159,  159,  159,  160,  160,
      160,  161,  161,  161,    0,  162,  162,  162,  151,  157,
      156,    0,    0,  153,  162,    0,    0,  163,  163,  163,
      154,  164,  164,  164,    0,    0,  161,  163,  165,  165,

      165,  166,  166,  166,  157,  156,  167,  167,  167,    0,
      162,    0,    0,  166,  165,  168,  168,  168,  169,  169,
      169,  161,    0,  163,  170,  170,  170,  171,  171,  171,
      169,  172,  172,  172,    0,    0,  170,    0,    0,  166,
      165,    0,  168,  173,  173,  173,  174,  174,  174,  175,
      175,  175,  176,  176,  176,    0,  169,  179,  179,  179,
        0,  175,  170,  177,  177,  177,    0,  168,  176,    0,
      173,  178,  178,  178,    0,  177,  180,  180,  180,  181,
      181,  181,    0,  178,  182,  182,  182,  175,  183,  183,
      183,  184,  184,  184,  176,  173,    0,    0,  182,    0,

        0,  177,  185,  185,  185,  186,  186,  186,    0,  178,
      187,  187,  187,  186,    0,  188,  188,  188,  184,  189,
      189,  189,    0,    0,  182,  188,  190,  190,  190,  191,
      191,  191,  192,  192,  192,    0,    0,  187,  190,  186,
      193,  193,  193,  184,    0,  189,  194,  194,  194,    0,
        0,  188,  195,  195,  195,  191,  196,  196,  196,  197,
      197,  197,  187,    0,  190,  198,  198,  198,    0,    0,
      189,    0,  195,  199,  199,  199,  200,  200,  200,    0,
      191,  201,  201,  201,    0,    0,  200,  202,  202,  202,
        0,    0,  197,  203,  203,  203,    0,    0,  195,  204,

      204,  204,  205,  205,  205,  206,  206,  206,  207,  207,
      207,    0,  200,  208,  208,  208,    0,  206,    0,    0,
      202,    0,  209,  209,  209,  210,  210,  210,    0,  207,
        0,  208,  209,    0,  207,  211,  211,  211,  212,  212,
      212,    0,    0,  206,  213,  213,  213,  211,  214,  214,
      214,  215,  215,  215,    0,  207,    0,  208,  209,  207,
      212,    0,    0,  214,    0,  216,  216,  216,  217,  217,
      217,    0,    0,  211,  218,  218,  218,  215,    0,    0,
      217,  219,  219,  219,    0,    0,  212,    0,    0,  214,
      216,    0,    0,  220,  220,  220,    0,  221,  221,  221,

        0,  218,  215,  220,    0,    0,  217,    0,  219,    0,
      222,  222,  222,    0,    0,  216,  221,  223,  223,  223,
        0,  224,  224,  224,    0,    0,  218,    0,    0,  220,
      222,    0,    0,  219,    0,  223,  225,  225,  225,  226,
      226,  226,  221,  224,  227,  227,  227,    0,  225,    0,
      228,  228,  228,  230,  230,  230,  222,  229,  229,  229,
        0,  223,  226,  231,  231,  231,  227,    0,    0,  224,
      232,  232,  232,    0,  225,  228,  230,  231,    0,  229,
      233,  233,  233,  234,  234,  234,  232,    0,  226,  235,
      235,  235,  227,    0,    0,  234,  236,  236,  236,    0,

      228,    0,  230,  231,    0,  229,  237,  237,  237,    0,
      235,    0,  232,  238,  238,  238,    0,    0,    0,    0,
        0,  234,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,  237,    0,    0,  235,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,  237,  240,
      240,  240,  241,  241,  241,  244,    0,  244,  245,    0,
      245,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,

      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lex.l"
#line 2 "lex.l"
    /* keywords are case insensitive */
    /* we don't need yywrap() function */
    /* we don't need yyunput() function */
    /* we don't need input() function */
#define YY_NO_INPUT 1
    /* enable location */
#include "ast.h"
#include "yacc.tab.h"
#include <iostream>

// automatically update location
#define YY_USER_ACTION \
    yylloc->first_line = yylloc->last_line; \
    yylloc->first_column = yylloc->last_column; \
    for (int i = 0; yytext[i] != '\0'; i++) { \
        if(yytext[i] == '\n') { \
            yylloc->last_line++; \
            yylloc->last_column = 1; \
        } else { \
            yylloc->last_column++; \
        } \
    }

#line 891 "lex.yy.cpp"

#line 893 "lex.yy.cpp"

#define INITIAL 0
#define STATE_COMMENT 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

YYSTYPE * yyget_lval ( void );

void yyset_lval ( YYSTYPE * yylval_param  );

       YYLTYPE *yyget_lloc ( void );
    
        void yyset_lloc ( YYLTYPE * yylloc_param  );
    
/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex \
               (YYSTYPE * yylval_param, YYLTYPE * yylloc_param );

#define YY_DECL int yylex \
               (YYSTYPE * yylval_param, YYLTYPE * yylloc_param )
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
        YYSTYPE * yylval;
    
        YYLTYPE * yylloc;
    
    yylval = yylval_param;

    yylloc = yylloc_param;

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 47 "lex.l"

#line 49 "lex.l"
    /* block comment */
#line 1131 "lex.yy.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 240 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1372 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 50 "lex.l"
{ BEGIN(STATE_COMMENT); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 51 "lex.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 52 "lex.l"
{ /* ignore the text of the comment */ }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 53 "lex.l"
{ /* ignore *'s that aren't part of */ }
	YY_BREAK
/* single line comment */
case 5:
YY_RULE_SETUP
#line 55 "lex.l"
{ /* ignore single line comment */ }
	YY_BREAK
/* white space and new line */
case 6:
YY_RULE_SETUP
#line 57 "lex.l"
{ /* ignore white space */ }
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 58 "lex.l"
{ /* ignore new line */ }
	YY_BREAK
/* keywords */
case 8:
YY_RULE_SETUP
#line 60 "lex.l"
{ return SHOW; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 61 "lex.l"
{ return TXN_BEGIN; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 62 "lex.l"
{ return TXN_COMMIT; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 63 "lex.l"
{ return TXN_ABORT; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 64 "lex.l"
{ return TXN_ROLLBACK; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 65 "lex.l"
{ return TABLES; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 66 "lex.l"
{ return CREATE; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 67 "lex.l"
{ return TABLE; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 68 "lex.l"
{ return DROP; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 69 "lex.l"
{ return DESC; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 70 "lex.l"
{ return INSERT; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 71 "lex.l"
{ return INTO; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 72 "lex.l"
{ return VALUES; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 73 "lex.l"
{ return DELETE; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 74 "lex.l"
{ return FROM; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 75 "lex.l"
{ return WHERE; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 76 "lex.l"
{ return UPDATE; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 77 "lex.l"
{ return SET; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 78 "lex.l"
{ return SELECT; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 79 "lex.l"
{ return INT; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 80 "lex.l"
{ return CHAR; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 81 "lex.l"
{ return FLOAT; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 82 "lex.l"
{ return DATETIME; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 83 "lex.l"
{ return INDEX; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 84 "lex.l"
{ return AND; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 85 "lex.l"
{return JOIN;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 86 "lex.l"
{ return EXIT; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 87 "lex.l"
{ return HELP; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 88 "lex.l"
{ return ORDER; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 89 "lex.l"
{  return BY;  }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 90 "lex.l"
{ return ASC; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 91 "lex.l"
{ return COUNT; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 92 "lex.l"
{ return MAX; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 93 "lex.l"
{ return MIN; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 94 "lex.l"
{ return SUM; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 95 "lex.l"
{ return AS; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 96 "lex.l"
{return GROUP;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 97 "lex.l"
{return HAVING;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 98 "lex.l"
{return IN;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 99 "lex.l"
{ return ENABLE_NESTLOOP; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 100 "lex.l"
{ return ENABLE_SORTMERGE; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 101 "lex.l"
{ return STATIC_CHECKPOINT; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 102 "lex.l"
{ return LOAD; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 103 "lex.l"
{ 
    yylval->sv_bool = true;
    return VALUE_BOOL; 
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 107 "lex.l"
{
    yylval->sv_bool = false;
    return VALUE_BOOL;
}
	YY_BREAK
/* operators */
case 53:
YY_RULE_SETUP
#line 112 "lex.l"
{ return GEQ; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 113 "lex.l"
{ return LEQ; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 114 "lex.l"
{ return NEQ; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 115 "lex.l"
{ return NEQ; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 116 "lex.l"
{ return yytext[0]; }
	YY_BREAK
/* id */
case 58:
YY_RULE_SETUP
#line 118 "lex.l"
{
    yylval->sv_str = yytext;
    return IDENTIFIER;
}
	YY_BREAK
/* literals */
case 59:
YY_RULE_SETUP
#line 123 "lex.l"
{
    yylval->sv_int = atoi(yytext);
    return VALUE_INT;
}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 127 "lex.l"
{
    yylval->sv_float = atof(yytext);
    return VALUE_FLOAT;
}
	YY_BREAK
case 61:
/* rule 61 can match eol */
YY_RULE_SETUP
#line 131 "lex.l"
{
    yylval->sv_str = std::string(yytext + 1, strlen(yytext) - 2);
    return VALUE_STRING;
}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 136 "lex.l"
{
    yylval->sv_str = yytext;
    return FILE_PATH_VALUE;
}
	YY_BREAK
/* EOF */
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(STATE_COMMENT):
#line 141 "lex.l"
{ return T_EOF; }
	YY_BREAK
/* unexpected char */
case 63:
YY_RULE_SETUP
#line 143 "lex.l"
{ std::cerr << "Lexer Error: unexpected character " << yytext[0] << std::endl; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 144 "lex.l"
ECHO;
	YY_BREAK
#line 1545 "lex.yy.cpp"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 240 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 240 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 239);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 144 "lex.l"


